services:
  - type: web
    name: nubeclinic
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nubeclinic-db
          property: connectionString

databases:
  - name: nubeclinic-db
    databaseName: nubeclinic
    user: nubeclinic_user